# Casa Perfecta - Agentie Imobiliara
site:
  name: Casa Perfecta - Agentie Imobiliara
  site: 'https://casaperfecta.ro'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Casa Perfecta - Agentie Imobiliara Bucuresti
    template: '%s | Casa Perfecta'
  description: 'Gaseste casa visurilor tale cu Casa Perfecta! Agentie imobiliara cu peste 15 ani experienta in Bucuresti. Apartamente, case, terenuri - vanzare si inchiriere.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Casa Perfecta - Agentie Imobiliara
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@casaperfecta'
    site: '@casaperfecta'
    cardType: summary_large_image

i18n:
  language: ro
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your Google Analytics ID here

ui:
  theme: 'light:only'
